databases:
  - name: runteq_portfolio_DB
    databaseName: runteq_portfolio_db
    user: portfolio
    region: singapore

services:
  - type: web
    name: portfolio
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: runteq_portfolio_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false